apiVersion: v1
kind: Service
metadata:
  name: userservice
  labels:
    app: userservice-deployment
spec:
  selector:
    app: userservice-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 30100
      targetPort: 30100
      nodePort: 30100
      name: userservice