# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notify.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='notify.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cnotify.proto\"(\n\x07message\x12\x0b\n\x03Msg\x18\x01 \x01(\t\x12\x10\n\x08\x65ligible\x18\x02 \x01(\x08\"\x16\n\x04stub\x12\x0e\n\x06userId\x18\x02 \x01(\t2-\n\x0b\x63\x61shBackApi\x12\x1e\n\x0bsendMessage\x12\x05.stub\x1a\x08.messageb\x06proto3')
)




_MESSAGE = _descriptor.Descriptor(
  name='message',
  full_name='message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Msg', full_name='message.Msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eligible', full_name='message.eligible', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=56,
)


_STUB = _descriptor.Descriptor(
  name='stub',
  full_name='stub',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='stub.userId', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['stub'] = _STUB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

message = _reflection.GeneratedProtocolMessageType('message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'notify_pb2'
  # @@protoc_insertion_point(class_scope:message)
  })
_sym_db.RegisterMessage(message)

stub = _reflection.GeneratedProtocolMessageType('stub', (_message.Message,), {
  'DESCRIPTOR' : _STUB,
  '__module__' : 'notify_pb2'
  # @@protoc_insertion_point(class_scope:stub)
  })
_sym_db.RegisterMessage(stub)



_CASHBACKAPI = _descriptor.ServiceDescriptor(
  name='cashBackApi',
  full_name='cashBackApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=82,
  serialized_end=127,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendMessage',
    full_name='cashBackApi.sendMessage',
    index=0,
    containing_service=None,
    input_type=_STUB,
    output_type=_MESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CASHBACKAPI)

DESCRIPTOR.services_by_name['cashBackApi'] = _CASHBACKAPI

# @@protoc_insertion_point(module_scope)
