# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Protos.notify_pb2 as notify_pb2


class cashBackApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendMessage = channel.unary_unary(
        '/cashBackApi/sendMessage',
        request_serializer=notify_pb2.stub.SerializeToString,
        response_deserializer=notify_pb2.message.FromString,
        )


class cashBackApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_cashBackApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.sendMessage,
          request_deserializer=notify_pb2.stub.FromString,
          response_serializer=notify_pb2.message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cashBackApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
