# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Protos.admin_parking_pb2 as admin_parking_pb2


class adminParkingApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.insert = channel.unary_unary(
        '/adminParkingApi/insert',
        request_serializer=admin_parking_pb2.toInsert.SerializeToString,
        response_deserializer=admin_parking_pb2.stub.FromString,
        )
    self.update = channel.unary_unary(
        '/adminParkingApi/update',
        request_serializer=admin_parking_pb2.toUpdate.SerializeToString,
        response_deserializer=admin_parking_pb2.stub.FromString,
        )


class adminParkingApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def insert(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_adminParkingApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'insert': grpc.unary_unary_rpc_method_handler(
          servicer.insert,
          request_deserializer=admin_parking_pb2.toInsert.FromString,
          response_serializer=admin_parking_pb2.stub.SerializeToString,
      ),
      'update': grpc.unary_unary_rpc_method_handler(
          servicer.update,
          request_deserializer=admin_parking_pb2.toUpdate.FromString,
          response_serializer=admin_parking_pb2.stub.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'adminParkingApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
