# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_parking.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user_parking.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12user_parking.proto\"\x16\n\x07message\x12\x0b\n\x03msg\x18\x01 \x01(\x08\"\x14\n\x04user\x12\x0c\n\x04user\x18\x01 \x01(\t22\n\x0euserParkingApi\x12 \n\rvalidate_user\x12\x05.user\x1a\x08.messageb\x06proto3')
)




_MESSAGE = _descriptor.Descriptor(
  name='message',
  full_name='message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='message.msg', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=44,
)


_USER = _descriptor.Descriptor(
  name='user',
  full_name='user',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='user.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['user'] = _USER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

message = _reflection.GeneratedProtocolMessageType('message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'user_parking_pb2'
  # @@protoc_insertion_point(class_scope:message)
  })
_sym_db.RegisterMessage(message)

user = _reflection.GeneratedProtocolMessageType('user', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_parking_pb2'
  # @@protoc_insertion_point(class_scope:user)
  })
_sym_db.RegisterMessage(user)



_USERPARKINGAPI = _descriptor.ServiceDescriptor(
  name='userParkingApi',
  full_name='userParkingApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=68,
  serialized_end=118,
  methods=[
  _descriptor.MethodDescriptor(
    name='validate_user',
    full_name='userParkingApi.validate_user',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_MESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERPARKINGAPI)

DESCRIPTOR.services_by_name['userParkingApi'] = _USERPARKINGAPI

# @@protoc_insertion_point(module_scope)
