# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin_parking.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='admin_parking.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x61\x64min_parking.proto\"n\n\x08toInsert\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\r\n\x05\x63\x61rId\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x61teIn\x18\x04 \x01(\t\x12\x0f\n\x07\x64\x61teOut\x18\x05 \x01(\t\x12\x10\n\x08isparked\x18\x06 \x01(\x08\"7\n\x08toUpdate\x12\r\n\x05\x63\x61rId\x18\x04 \x01(\t\x12\x0b\n\x03loc\x18\x05 \x01(\t\x12\x0f\n\x07\x64\x61teOut\x18\x01 \x01(\t\"\x06\n\x04stub2I\n\x0f\x61\x64minParkingApi\x12\x1a\n\x06insert\x12\t.toInsert\x1a\x05.stub\x12\x1a\n\x06update\x12\t.toUpdate\x1a\x05.stubb\x06proto3')
)




_TOINSERT = _descriptor.Descriptor(
  name='toInsert',
  full_name='toInsert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='toInsert.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='carId', full_name='toInsert.carId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='toInsert.location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dateIn', full_name='toInsert.dateIn', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dateOut', full_name='toInsert.dateOut', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isparked', full_name='toInsert.isparked', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=133,
)


_TOUPDATE = _descriptor.Descriptor(
  name='toUpdate',
  full_name='toUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='carId', full_name='toUpdate.carId', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loc', full_name='toUpdate.loc', index=1,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dateOut', full_name='toUpdate.dateOut', index=2,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=190,
)


_STUB = _descriptor.Descriptor(
  name='stub',
  full_name='stub',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=198,
)

DESCRIPTOR.message_types_by_name['toInsert'] = _TOINSERT
DESCRIPTOR.message_types_by_name['toUpdate'] = _TOUPDATE
DESCRIPTOR.message_types_by_name['stub'] = _STUB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

toInsert = _reflection.GeneratedProtocolMessageType('toInsert', (_message.Message,), {
  'DESCRIPTOR' : _TOINSERT,
  '__module__' : 'admin_parking_pb2'
  # @@protoc_insertion_point(class_scope:toInsert)
  })
_sym_db.RegisterMessage(toInsert)

toUpdate = _reflection.GeneratedProtocolMessageType('toUpdate', (_message.Message,), {
  'DESCRIPTOR' : _TOUPDATE,
  '__module__' : 'admin_parking_pb2'
  # @@protoc_insertion_point(class_scope:toUpdate)
  })
_sym_db.RegisterMessage(toUpdate)

stub = _reflection.GeneratedProtocolMessageType('stub', (_message.Message,), {
  'DESCRIPTOR' : _STUB,
  '__module__' : 'admin_parking_pb2'
  # @@protoc_insertion_point(class_scope:stub)
  })
_sym_db.RegisterMessage(stub)



_ADMINPARKINGAPI = _descriptor.ServiceDescriptor(
  name='adminParkingApi',
  full_name='adminParkingApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=200,
  serialized_end=273,
  methods=[
  _descriptor.MethodDescriptor(
    name='insert',
    full_name='adminParkingApi.insert',
    index=0,
    containing_service=None,
    input_type=_TOINSERT,
    output_type=_STUB,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='adminParkingApi.update',
    index=1,
    containing_service=None,
    input_type=_TOUPDATE,
    output_type=_STUB,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADMINPARKINGAPI)

DESCRIPTOR.services_by_name['adminParkingApi'] = _ADMINPARKINGAPI

# @@protoc_insertion_point(module_scope)
