apiVersion: v1
kind: Service
metadata:
  name: adminservice
  labels:
    app: adminservice-deployment
spec:
  selector:
    app: adminservice-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 8083
      name: adminservice
      nodePort: 31845
