apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adminservice-deployment
  template:
    metadata:
      labels:
        app: adminservice-deployment
    spec:
      containers:
        - name: adminservice
          image: adminservice
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8083