apiVersion: v1
kind: Service
metadata:
  name: parkingdbmirror
  labels:
    app: parkingdbmirror
spec:
  ports:
    - name: parkingdbmirror
      protocol: TCP
      port: 5432
  selector:
   app: parkingdbmirror