"""empty message

Revision ID: 96b5e4345225
Revises: 
Create Date: 2019-07-19 00:10:50.745061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b5e4345225'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking',
    sa.Column('parking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('car_id', sa.String(length=10), nullable=False),
    sa.Column('date_in', sa.DATE(), nullable=True),
    sa.Column('date_out', sa.DATE(), nullable=True),
    sa.Column('location', sa.String(length=10), nullable=False),
    sa.Column('isparked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('parking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parking')
    # ### end Alembic commands ###
