# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Protos.user_parking_pb2 as user_parking_pb2


class userParkingApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.validate_user = channel.unary_unary(
        '/userParkingApi/validate_user',
        request_serializer=user_parking_pb2.user.SerializeToString,
        response_deserializer=user_parking_pb2.message.FromString,
        )


class userParkingApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def validate_user(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_userParkingApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'validate_user': grpc.unary_unary_rpc_method_handler(
          servicer.validate_user,
          request_deserializer=user_parking_pb2.user.FromString,
          response_serializer=user_parking_pb2.message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'userParkingApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
